org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.20.1
loader_version=0.19.3

mod_version=1.2.0
maven_group=net.superkat.wavify
archives_base_name=wavify

fabric_version=0.92.11+1.20.1
midnightlib_version=1.9.3+1.20.1-fabric
modmenu_version=7.2.2
