org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=wavify
mod_name=Wavify
mod_license=MIT
mod_version=1.2.0
mod_group_id=net.superkat.wavify
mod_authors=Superkat32
mod_description=Dynamic ocean, shoreline, and river waves for Minecraft.
