modLoader="javafml"
loaderVersion="[3,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Superkat32/Wavify/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
modUrl="https://modrinth.com/mod/wavify-waves"
bannerFile="assets/wavify/icon.png"
iconFile="assets/wavify/icon.png"
authors="Superkat32"
description='''Adds ambient tidal waves to beaches, oceans and rivers!'''

[[mixins]]
config="wavify.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
