modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Superkat32/Wavify/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
modUrl="https://modrinth.com/mod/wavify-waves"
logoFile="assets/wavify/icon.png"
description='''
Dynamic ocean, shoreline, and river waves for Minecraft.

Wavify adds ambient water motion to Minecraft with dedicated ocean and river wave systems, shader-aware rendering offsets, ambient shoreline audio, and off-thread scanning to keep wave generation smooth.
'''

[[mixins]]
config="wavify.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dynamicwaters"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
